### ISSUE TITLE
datacontract export --format bigquery

### ISSUE THREAD

**Issue by simonharrer** [datacontract/datacontract-cli#111]
Export to BigQuery schema

**Comment by jochenchrist** [comment]
This issue is stale.
Anyone interested in this feature?

**Comment by jochenchrist** [comment]
Closing issue as stale. Please reopen if you need this feature.

**Comment by jochenchrist** [comment]
Option Export as table reference
---

To be used by the BigQuery REST API:

https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#Table

```
{
      "tableReference": {
        "projectId": "my-project",
        "datasetId": "my_dataset",
        "tableId": "my_table"
      },
      "description": "This is a description",
      "type": "TABLE",
      "schema": {
        "fields": [
          {
            "name": "name",
            "type": "STRING",
            "mode": "NULLABLE",
            "description": "This is a description"
          }
        ]
      }
    }
```

**Comment by jochenchrist** [comment]
Option Export as gcloud deployment YAML File

```
resources:
- name: TestTableYAML
  type:  bigquery.v2.table
  properties:
   datasetId: test_dataset
   tableReference:
     projectId: testgcpproject
     tableId: TestTableYAML
   description: TestTableYAML
   labels:
     apigateway: not-applicable
   schema:
     fields:
       - mode: nullable 
         name: ID 
         type: string
```
