### ISSUE TITLE
Add support for Azure Data Lake

### ISSUE THREAD

**Issue by simonharrer** [datacontract/datacontract-cli#146]
See https://www.linkedin.com/feed/update/urn:li:activity:7185928487696801793?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7185928487696801793%2C7185984010190217216%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287185984010190217216%2Curn%3Ali%3Aactivity%3A7185928487696801793%29

**Comment by jochenchrist** [comment]
DuckDB has an extension to connect to ADLS (and Blob Storage):
https://duckdb.org/docs/extensions/azure.html

**Comment by jochenchrist** [comment]
Server Configuration could look like this (needs to be added to Data Contract Specification):

```
servers:
  production:
    type: adls
    location: abfss://⟨my_filesystem/⟨path⟩/⟨my_file⟩.⟨parquet_or_csv⟩
    format: parquet # parquet, csv, json
    delimiter: new_line # for json
```
