### ISSUE TITLE
Missing data type in Snowflake

### ISSUE THREAD

**Issue by anamargaridarl** [datacontract/datacontract-cli#150]
Hi, 

While working I found that the Snowflake [converter](https://github.com/datacontract/datacontract-cli/blob/03aa6cef5fa56c5cc631c1868d564a4aee6dce97/datacontract/export/sql_type_converter.py#L31) is missing a data type - TIMESTAMP_LTZ. 

For example, CURRENT_TIMESTAMP() returns this data type.

Could you please add it to the converter? I am willing to do it but have lack of permissions to push branches to your repository.

Thank you, 
Ana Loureiro

**Comment by jochenchrist** [comment]
The current Data Contract [Data Types](https://datacontract.com/#data-types) do not support a timestamp in the current session's timezone, as Snowflake's TIMESTAMP_LTZ does.

Do you really need this date format? I'd consider storing the timestamp in UTC.

**Comment by jochenchrist** [comment]
See discussion in: https://github.com/datacontract/datacontract-specification/issues/63

**Comment by jochenchrist** [comment]
You now can specify the `snowflakeType` in `config`:

```
      PROCESSING_TIMESTAMP:
        description: The processing timestamp in the current session’s time zone.
        type: timestamp
        required: true
        config:
          snowflakeType: TIMESTAMP_LTZ
```
