### ISSUE TITLE
Server type azure not yet supported by datacontract CLI

### ISSUE THREAD

**Issue by john-bunge-ed** [datacontract/datacontract-cli#169]
Hi!

Contrary to what is suggested [here](https://cli.datacontract.com/) ("Data Contract CLI can test data that is stored in Azure Blob storage or Azure Data Lake Storage (Gen2) (ADLS) in various formats.") I got the following error message when testing a data contract against data stored on ADLS Gen2:

`WARNING:root:Server type azure not yet supported by datacontract CLI`

Here is the relevant part of the yaml file:

```
servers:
  production:
    type: azure
    location: abfss://teststorage<redacted>.dfs.core.windows.net/Bronze/datacontract_test/*.parquet
    format: parquet
```

And here the code to run the test:

```
from datacontract.data_contract import DataContract

data_contract_02 = DataContract(data_contract_file="datacontract-example-02.yaml")
run_02 = data_contract_02.test()
```

Anything I did wrong to make this run?
