### ISSUE TITLE
Test data contract against dataframes or views

### ISSUE THREAD

**Issue by john-bunge-ed** [datacontract/datacontract-cli#175]
Hi!

during my tests with this package I ran:

```
data_contract = DataContract(data_contract_file="datacontract.yaml")
run = data_contract.test()
```

I learnt that in `datacontract.yaml` I can specify a data source in the *server* block. 

Question: Do I also have the option to tests the contract against a Python or PySpark dataframe at runtime, or against a (temporary) SQL view? 

Motivation: I do not want to persist the data I am testing the contract against. I am asking this from a Databricks perspective, but this questions is also relevant if I have some data transformation pipeline in Python which runs locally, and I want to test the data contract against a specific dataframe created during that pipeline.

**Comment by jochenchrist** [comment]
Currently, you cannot test a dataframe at runtime. 

With Databricks, the recommended way is to use a Unity Catalog or Hive table.
And you can define the spark session:

```
data_contract = DataContract(
  data_contract_file="/Volumes/.../datacontract.yaml", 
  spark=spark
)
run = data_contract.test()
run.result
```

datacontract.yaml
```
servers:
  production:
    type: databricks
    host: dbc-xxx.cloud.databricks.com
    catalog: datacontract_test_2
    schema: orders_latest
```
