### ISSUE TITLE
AVRO Schema - Array import error

### ISSUE THREAD

**Issue by pixie79** [datacontract/datacontract-cli#181]
I am getting the following error importing an AVRO Schema with a type of array.

DataContractException: Run operation failed: [schema] Map avro type to data contract type - None - failed - Unsupported type array in avro schema. - datacontract

```json
{
  "name": "nationalities",
  "type": [
    "null",
    {
      "type": "array",
      "items": {
        "type": "string",
        "connect.parameters": {
          "avro.java.string": "String"
        },
        "avro.java.string": "String"
      }
    }
  ],
  "doc": "Nationality of the registered party as code to identify a country, a dependency, or another area of particular geopolitical interest, on the basis of country names obtained from the United Nations (ISO 3166, Alpha-3 code)",
  "default": null
}
```

**Comment by jochenchrist** [comment]
Hi @pixie79,

an array at top-level is currently not supported, the importer expects a `fields` list.

Could you elaborate your use case for this AVRO schema and how the expected data contract shoud look like?

**Comment by pixie79** [comment]
Hi

Sorry I was trying to just cut out the effected line from the Avro schema, I have made a slightly larger version now (it is part of a schema supplied by a partner so I can not supply a full version.

```json
{
    "type": "record",
    "name": "CustomerEvent",
    "fields": [
        {
            "name": "business_data_payload",
            "type": {
                "type": "record",
                "name": "Customer",
                "fields": [
                    {
                        "name": "citizenship",
                        "type": [
                            "null",
                            {
                                "type": "record",
                                "name": "ClientCitizenship",
                                "fields": [
                                    {
                                        "name": "nationalities",
                                        "type": [
                                            "null",
                                            {
                                                "type": "array",
                                                "items": {
                                                    "type": "string"
                                                }
                                            }
                                        ],
                                        "doc": "Nationality of the registered party as code to identify a country, a dependency, or another area of particular geopolitical interest, on the basis of country names obtained from the United Nations (ISO 3166, Alpha-3 code)",
                                        "default": null
                                    },
                                    {
                                        "name": "created_date",
                                        "type": {
                                            "type": "long",
                                            "logicalType": "timestamp-millis"
                                        },
                                        "doc": "When this nationality was associated to the party"
                                    },
                                    {
                                        "name": "updated_date",
                                        "type": {
                                            "type": "long",
                                            "logicalType": "timestamp-millis"
                                        },
                                        "doc": "Date when nationality was updated for this party"
                                    }
                                ]
                            }
                        ],
                        "default": null
                    }
                ]
                }
            }
    ]
}
```

As you can see the Array is nested several levels deep and would allow for an answer of something like the following options:
- "null"
- "GBR"
- "GBR","USA"

**Comment by pixie79** [comment]
I think I am expecting a data contract that would look like this:

```yml
dataContractSpecification: 0.9.3
id: my-data-contract-id
info:
  title: My Data Contract
  version: 0.0.1
models:
  CustomerEvent:
    fields:
      business_data_payload:
        type: object
        required: true
        fields:
          citizenship:
            type: record
            required: false
            fields:
              created_date:
                type: long
                required: true
                description: When this nationality was associated to the party
              updated_date:
                type: long
                required: true
                description: Date when nationality was updated for this party
              nationalities:
                type: array
                required: false
                items:
                  type: string
                  required: true
                  description: Nationality of the registered party as code to identify a country, a dependency, or another area of particular geopolitical interest, on the basis of country names obtained from the United Nations (ISO 3166, Alpha-3 code)
```
