### ISSUE TITLE
Export to jsonschema fails if object Field contains no subfields

### ISSUE THREAD

**Issue by hcrosse** [datacontract/datacontract-cli#218]
I'm encountering a `StopIteration` error [on this line](https://github.com/datacontract/datacontract-cli/blob/2908e2f999abd9ba49128a3d58b5f953c659ebf1/datacontract/export/jsonschema_converter.py#L57) when trying to export from a model that contains a Field of `type: object`  but contains no subfields. The jsonschema specification allows for empty objects so this seems like an unintentional error rather than deliberate decision.

Example model that fails
```
models:
  A:
    title: A
    description: ABC
    type: object
    fields:
       B:
        type: object
        description: BCD
```
