### ISSUE TITLE
sqlserver not supported by datacontract CLI

### ISSUE THREAD

**Issue by Thrit** [datacontract/datacontract-cli#229]
When picking sqlserver as my server type I get the following error during the tests stage.

Example:
```
servers:
  production:
    type: sqlserver
    host: fake-sqlserver.example.com
    port: 1433
    database: database
    schema: dbo
```

Warning: `Server type sqlserver not yet supported by datacontract CLI`

Any idea to fix it?

**Comment by jochenchrist** [comment]
sqlserver support is not yet released and is planned for v0.10.5, will be released probably this week (https://github.com/datacontract/datacontract-cli/blob/main/CHANGELOG.md)

You could test it with the latest development version:
https://github.com/datacontract/datacontract-cli?tab=readme-ov-file#development-setup

**Comment by Thrit** [comment]
> sqlserver support is not yet released and is planned for v0.10.5, will be released probably this week (https://github.com/datacontract/datacontract-cli/blob/main/CHANGELOG.md)
> 
> You could test it with the latest development version: https://github.com/datacontract/datacontract-cli?tab=readme-ov-file#development-setup

Great! Thanks for the quick reply. 

By the way, I just came across this library today and it's a lifesaver. Thanks for that 😁

**Comment by jochenchrist** [comment]
data contract `v0.10.6` has been released 🎉.

@Thrit can you test if it works for you?

**Comment by Thrit** [comment]
> data contract `v0.10.6` has been released 🎉.
> 
> @Thrit can you test if it works for you?

Happy days 🎉 

Sure, I’ll get back to you soon.

**Comment by Thrit** [comment]
So, I'm still facing some issues when running the test command.

This is my environment:
- Python 3.12.3
- datacontract-cli==0.10.6

My datacontract has these values for the servers section:
```yaml
servers:
  production:
    type: sqlserver
    host: sqlserver-fake-host.database.windows.net
    port: 1433
    database: database
    schema: dbo
```

Running the command `datacontract test datacontract.yaml` I get the following message: `ERROR:soda.scan:[21:16:16] Could not connect to data source "sqlserver": Encountered a problem while trying to connect to sqlserver: can only concatenate str (not "NoneType") to str`.

I was debugging the functions that led to the error and encountered the moment when the variable returned `None`.

The error occurs in the `_parse_configuration_yaml_str` function (Line 180) in the scan.py.

When line 184 runs, it returns:
```yaml
data_source sqlserver:
  database: database
  driver: null
  encrypt: true
  host: sqlserver-fake-host.database.windows.net
  password: ''
  port: '1433'
  schema: dbo
  trust_server_certificate: false
  trusted_connection: false
  type: sqlserver
  username: ''
```

After instancing the `ConfigurationParser`, at line 191 is where I get the `NoneType` value.


I will come back to the code afterwards.

**Comment by jochenchrist** [comment]
Do you need to specific the driver?


```
servers:
  production:
    type: sqlserver
    host: sqlserver-fake-host.database.windows.net
    port: 1433
    database: database
    schema: dbo
    driver: ODBC Driver 18 for SQL Server
```
