### ISSUE TITLE
Adding S3 delta support

### ISSUE THREAD

**Issue by stepjaco** [datacontract/datacontract-cli#24]
Is there a timeline / estimate for when S3 Delta or Databricks Server Objects might be available?

e.g. 
```
servers:
  production:
   type: s3
   location: s3://...
   format: delta
   delimiter: new_line
```

This tool looks like it has a lot of potential.
Thanks for all the great work so far.
