### ISSUE TITLE
Feature Request: datacontract-cli as pre-commit hook

### ISSUE THREAD

**Issue by burakince** [datacontract/datacontract-cli#279]
Hi everyone,

I'd like to provide some context before diving into the details. [pre-commit](https://pre-commit.com/) is an open-source project that simplifies defining [git pre-commit hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks). Our project is already utilizing a defined pre-commit hook, which you can view [here](https://github.com/datacontract/datacontract-cli/blob/main/.pre-commit-config.yaml).

This feature request proposes that `datacontract-cli` should be described as a **pre-commit hook** for the `lint` subcommand. To achieve this, we need to create a `.pre-commit-hooks.yaml` file. For more detailed information, please refer to the guidelines [here](https://pre-commit.com/#creating-new-hooks).

Here is an example of how the usage could look:

_Example `.pre-commit-config.yaml` definition:_

```yaml
repos:
  - repo: https://github.com/datacontract/datacontract-cli
    rev: "v0.10.9"
    hooks:
      - id: datacontract-linting
```

This repository should contain at least the following file and configuration:

_Example `.pre-commit-hooks.yaml` definition:_

```yaml
- id: datacontract-linting
  name: Data Contract Linter
  description: This hook lints the data contract.
  entry: datacontract lint
  files: "datacontract*.yaml"
  language: python
  types: [yaml]
```

Thank you all for your assistance.

Best regards,  
Burak Ince
