### ISSUE TITLE
Export to jsonschema drops field traits when set to zero

### ISSUE THREAD

**Issue by Figueus** [datacontract/datacontract-cli#281]
When exporting a datacontract to jsonschema it seems to drop the minimum and maximum field traits if they are set to 0.

Example:
```yml
[...]
models:
  my_model:
    description: testing minmax
    type: table
    fields:
      mintest:
        type: number
        minimum: 0
        maximum: 100
        description: Testing minimum on zero
      maxtest:
        type: number
        minimum: -100
        maximum: 0
        description: Testing maximum on zero
      onlyminimum:
        type: number
        minimum: 0
      onlymaximum:
        type: number
        maximum: 0
      all:
        type: number
        minimum: 0
        maximum: 0
        description: Both on zero
[...]
```
Executed command:
`datacontract export --format jsonschema`

Expected result:
```json
[...]
  "properties": {
    "mintest": {
      "type": [
        "number",
        "null"
      ],
      "description": "Testing minimum on zero",
      "minimum": 0,
      "maximum": 100
    },
    "maxtest": {
      "type": [
        "number",
        "null"
      ],
      "description": "Testing maximum on zero",
      "minimum": -100,
      "maximum": 0
    },
    "onlyminimum": {
      "type": [
        "number",
        "null"
      ],
      "minimum": 0
    },
    "onlymaximum": {
      "type": [
        "number",
        "null"
      ],
      "maximum": 0
    },
    "all": {
      "type": [
        "number",
        "null"
      ],
      "minimum": 0,
      "maximum": 0,
      "description": "Both on zero"
    }
  }
[...]
```

Actual result:
```json
[...]
  "properties": {
    "mintest": {
      "type": [
        "number",
        "null"
      ],
      "description": "Testing minimum on zero",
      "maximum": 100
    },
    "maxtest": {
      "type": [
        "number",
        "null"
      ],
      "description": "Testing maximum on zero",
      "minimum": -100
    },
    "onlyminimum": {
      "type": [
        "number",
        "null"
      ]
    },
    "onlymaximum": {
      "type": [
        "number",
        "null"
      ]
    },
    "all": {
      "type": [
        "number",
        "null"
      ],
      "description": "Both on zero"
    }
  }
[...]
```

As you can see the minimum and maximum values that are set to zero are removed.

After taking a look at the source I wonder if [this if-statement in the jsonconverter](https://github.com/datacontract/datacontract-cli/blob/0305cd799f73bfa04dc51d4f18427cbdda0282f1/datacontract/export/jsonschema_converter.py#L73) might resolve to a falsy value, causing it to not be included in the output.
```python
    if field.minimum:
        property["minimum"] = field.minimum
```
