### ISSUE TITLE
Wrong type detection on varchar field type on Model

### ISSUE THREAD

**Issue by mustafaileri** [datacontract/datacontract-cli#298]
The field type return varchar(XXX)
In my case: Type Mismatch, Expected Type: STRING; Actual Type: varchar(100)

This is my definition:
```yaml    
field_name:
        description: Field desc
        type: varchar
        maxLength: 100
        required: false
```

When I run the test command it returns the error message.  My server type is: Databricks.

**Comment by jochenchrist** [comment]
You can overwrite the physical type using the [config option](https://datacontract.com/#config-object):

Can you try this:

```
field_name:
        description: Field desc
        type: varchar
        maxLength: 100
        config:
            databricksType: varchar(100)
        required: false
```
