### ISSUE TITLE
import dbt source into datacontrac

### ISSUE THREAD

**Issue by SabineGl** [datacontract/datacontract-cli#349]
datacontract version 0.10.10
command:
datacontract import --format dbt --source dbt_test.yml

Usage: datacontract import [OPTIONS]
Create a data contract from the given source location. Prints to stdout.

--format [sql|avro|dbt|glue|jsonschema|bigquery|odcs|unity|spark] The format of the source file. [default: None] [required]
I tested folowing dbt source.yml file to import (see below) and got following error:

`JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

``` 
version: 2
models:
  - name: customers
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders
    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
      - name: first_name
        description: Customer's first name. PII.
      - name: last_name
        description: Customer's last name. PII.
      - name: first_order
        description: Date (UTC) of a customer's first order
      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order
      - name: number_of_orders
        description: Count of the number of orders a customer has placed
      - name: total_order_amount
        description: Total value (AUD) of a customer's orders
 ```
