### ISSUE TITLE
Feature: AWS Athena import

### ISSUE THREAD

**Issue by roykoand** [datacontract/datacontract-cli#359]
Would you mind if I add AWS Athena as a separate possible Import format? 
I want to have something in a pocket, so when Bitol RFC-0007 will be confirmed I can run SQL tests on a top of it (@jochenchrist thanks for pointing me to this specification!):
```
quality:
  - type: sql 
    query: |
      SELECT COUNT(*) FROM ${table} WHERE ${column} IS NOT NULL
    mustBeLessThan: 3600 
```
