### ISSUE TITLE
Service Levels Should Perform Tests Natively 

### ISSUE THREAD

**Issue by dataGriff** [datacontract/datacontract-cli#407]
For the following nodes in the `servicelevels` datacontract specification:

* `retention`
* `latency`
* `freshness`

Tests should automatically occur on the properties available without needing to specify them further in the additional `quality` node as everything is available to perform these tests without further specification.

```yaml
retention:
   description: Data is retained for one year
   period: P1Y
   timestampField: model_name.last_updated
   unlimited: false
  latency:
    description: Data is available within 25 hours after the order was placed
    threshold: 1m
    sourceTimestampField: model_name.last_updated
    processedTimestampField: model_name.last_updated
  freshness:
    description: The most recent data in the whiskeys list.
    threshold: 1m
    timestampField: model_name.last_updated
```
