### ISSUE TITLE
Optional fields in examples

### ISSUE THREAD

**Issue by ryancollingwood** [datacontract/datacontract-cli#409]
# The Issue

**Environment:**
- `datacontract-cli==0.10.11`
- python 3.11
- MacOS

**What I'm  trying to do:**
Define some examples (https://datacontract.com/#example-object) in the datacontract and then test the examples via: `datacontract test contract.yml --examples`

In my contract I have a field that could be `null` (or `None` in python terms).  
I have specified two example cases: one where all fields are specified and one where the optional field is omitted

```yaml
dataContractSpecification: 0.9.3
id: 1917cdd6-b418-4ddd-9000-82c9f2cf0448
info:
  title: Customer RFM
  version: 0.0.1
  description: "RFM analysis is a technique for ranking and grouping customers based on their transaction history over a fixed period to inform which marketing campaigns to target which specific customers.\nFor each customer we require the following data for the period in question:\n•\tRecency: The number of days since the customer last made a purchase in the period.\n•\tFrequency: The number of transactions the customer completed in the period.\n•\tMonetary: The total sum of spending by the customer in the period."
  status: proposed
  owner: store-technologies
models:
  customer_rfm:
    type: table
    description: Details the RFM for each customer on weekly basis
    title: Customer RFM
    fields:
      CustomerID:
        type: number
        description: Uniquely identifies a customer
        required: true
        scale: 0
        minimum: 1
      AsOfDate:
        type: date
        description: Date when the values were calculated
        required: true
      NumTransactions:
        type: int
        description: "Number of transactions the customer has completed, can have multiple transactions on a given day"
        required: true
        minimum: 0
      SumSalesValue:
        type: number
        description: "Summed value of the customers sales, excluding tax"
        required: true
        minimum: 0
      LastTransactionDate:
        type: date
        description: The date of the most recent transaction for the customer
        required: false
examples:
- type: json
  model: customer_rfm
  description: Customers that have made a purchase
  data:
    - CustomerID: 1234
      AsOfDate: "2024-09-01"
      NumTransactions: 2
      SumSalesValue: 349.95
      LastTransactionDate: "2024-07-12"
- type: json
  model: customer_rfm
  description: Customers that haven't made a purchase
  data:
    - CustomerID: 5678
      AsOfDate: "2024-09-01"
      NumTransactions: 0
      SumSalesValue: 0
```

If I attempt to test my examples:
```python
from datacontract.data_contract import DataContract

if __name__ == "__main__":

    dc = DataContract(data_contract_file="contract.yml", examples=True)

    run = dc.test()
    run_result = run.result
    print("run result:", run.result)
    for log in run.logs[-10:]:
        print(log.message)
```

I get the following output:
```bash
Column,Event,Details
LastTransactionDate,:icon-fail: Required Column Missing, 

Required Column Missing,
run result: failed
      Check that required field NumTransactions has no null values [PASSED]
      Check that field NumTransactions has a minimum of 0 [PASSED]
      Check that required field SumSalesValue has no null values [PASSED]
      Check that field SumSalesValue has a minimum of 0 [PASSED]
1/12 checks FAILED: 
    customer_rfm in local
      Check that field LastTransactionDate is present [FAILED]
        fail_missing_column_names = [LastTransactionDate]
        schema_measured = [CustomerID bigint, AsOfDate date, NumTransactions bigint, SumSalesValue bigint]
Oops! 1 failures. 0 warnings. 0 errors. 11 pass.
```

However if I update the optional field test case to have the field present with a null value
```yaml
...
  description: Customers that haven't made a purchase
  data:
    - CustomerID: 5678
      AsOfDate: "2024-09-01"
      NumTransactions: 0
      SumSalesValue: 0
      LastTransactionDate: null
```

I get the following output when running the script
```bash
ERROR:root:Run operation failed: [schema] Check that JSON has valid schema - customer_rfm - failed - data.LastTransactionDate must be string - jsonschema
run result: failed
Testing data contract
Copying examples to files in temporary directory /var/folders/7y/06_hrjnx72s2pd6czl9kkslc0000gn/T/datacontract-cliurwjkgpc
Creating example file /var/folders/7y/06_hrjnx72s2pd6czl9kkslc0000gn/T/datacontract-cliurwjkgpc/customer_rfm.json
Creating example file /var/folders/7y/06_hrjnx72s2pd6czl9kkslc0000gn/T/datacontract-cliurwjkgpc/customer_rfm.json
Using type='local' description=None environment=None format='json' project=None dataset=None path='/var/folders/7y/06_hrjnx72s2pd6czl9kkslc0000gn/T/datacontract-cliurwjkgpc/{model}.json' delimiter='array' endpointUrl=None location=None account=None database=None schema_=None host=None port=None catalog=None topic=None http_path=None token=None dataProductId=None outputPortId=None driver=None for testing the examples
Running tests for data contract 1917cdd6-b418-4ddd-9000-82c9f2cf0448 with server examples
Running engine jsonschema
jsonschema: Converting model customer_rfm to JSON Schema
jsonschema: {'$schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object', 'properties': {'CustomerID': {'type': 'number', 'description': 'Uniquely identifies a customer', 'minimum': 1}, 'AsOfDate': {'type': 'string', 'format': 'date', 'description': 'Date when the values were calculated'}, 'NumTransactions': {'type': 'integer', 'description': 'Number of transactions the customer has completed, can have multiple transactions on a given day', 'minimum': 0}, 'SumSalesValue': {'type': 'number', 'description': 'Summed value of the customers sales, excluding tax', 'minimum': 0}, 'LastTransactionDate': {'type': 'string', 'format': 'date', 'description': 'The date of the most recent transaction for the customer'}}, 'required': ['CustomerID', 'AsOfDate', 'NumTransactions', 'SumSalesValue'], 'title': 'Customer RFM', 'description': 'Details the RFM for each customer on weekly basis'}
Run operation failed: [schema] Check that JSON has valid schema - customer_rfm - failed - data.LastTransactionDate must be string - jsonschema
```

# My Investigation

## datacontract.export.jsonschema_converter.to_property
At present we're not evaluating the `required` field specification in the contract - we could do this and then in generating the jsonschema version state that the allowed types are the given type and `"null"` - see: https://json-schema.org/understanding-json-schema/reference/type#:~:text=The%20type%20keyword%20may%20either%20be%20a%20string%20or%20an%20array%3A

## DataContracy._get_examples_server
When constructing from sample data we could make allowance for missing fields that are optional, although probably an overreach as I'd prefer to explicitly state a field is `null` for the purposes of examples - but it may be something worth considering

## Monkey Patched Script
Given the above here's  monkey patched script that works
```python
import json
import yaml
import logging

from datacontract.data_contract import DataContract
import datacontract

from datacontract.export.jsonschema_converter import to_properties, convert_type_format, to_required
from datacontract.model.data_contract_specification import Field, Server

if __name__ == "__main__":
    def monkey_patch_to_property(field: Field) -> dict:
        property = {}
        json_type, json_format = convert_type_format(field.type, field.format)
        if json_type is not None:
            if not field.required:
                """
                From: https://json-schema.org/understanding-json-schema/reference/type
                The type keyword may either be a string or an array:

                If it's a string, it is the name of one of the basic types above.
                If it is an array, it must be an array of strings, where each string 
                is the name of one of the basic types, and each element is unique.
                In this case, the JSON snippet is valid if it matches any of the given types.
                """
                property["type"] = [json_type, "null"]
            else:
                property["type"] = json_type
        if json_format is not None:
            property["format"] = json_format
        if field.unique:
            property["unique"] = True
        if json_type == "object":
            # TODO: any better idea to distinguish between properties and patternProperties?
            if field.fields.keys() and next(iter(field.fields.keys())).startswith("^"):
                property["patternProperties"] = to_properties(field.fields)
            else:
                property["properties"] = to_properties(field.fields)
            property["required"] = to_required(field.fields)
        if json_type == "array":
            property["items"] = monkey_patch_to_property(field.items)

        if field.pattern:
            property["pattern"] = field.pattern
        if field.enum:
            property["enum"] = field.enum
        if field.minLength is not None:
            property["minLength"] = field.minLength
        if field.maxLength is not None:
            property["maxLength"] = field.maxLength
        if field.title:
            property["title"] = field.title
        if field.description:
            property["description"] = field.description
        if field.exclusiveMinimum is not None:
            property["exclusiveMinimum"] = field.exclusiveMinimum
        if field.exclusiveMaximum is not None:
            property["exclusiveMaximum"] = field.exclusiveMaximum
        if field.minimum is not None:
            property["minimum"] = field.minimum
        if field.maximum is not None:
            property["maximum"] = field.maximum
        if field.tags:
            property["tags"] = field.tags
        if field.pii:
            property["pii"] = field.pii
        if field.classification is not None:
            property["classification"] = field.classification

        # TODO: all constraints
        return property
    
    def monkey_patch_get_examples_server(data_contract, run, tmp_dir):
        run.log_info(f"Copying examples to files in temporary directory {tmp_dir}")
        format = "json"
        for example in data_contract.examples:
            # determine optional fields
            optional_fields = [k for k,v in data_contract.models[example.model].fields.items() if not v.required]

            format = example.type
            p = f"{tmp_dir}/{example.model}.{format}"
            run.log_info(f"Creating example file {p}")
            with open(p, "w") as f:
                content = ""
                if format == "json" and isinstance(example.data, list):
                    content = json.dumps(example.data)
                elif format == "json" and isinstance(example.data, str):
                    content = example.data
                elif format == "yaml" and isinstance(example.data, list):
                    content = yaml.dump(example.data, allow_unicode=True)
                elif format == "yaml" and isinstance(example.data, str):
                    content = example.data
                elif format == "csv":
                    content = example.data
                logging.debug(f"Content of example file {p}: {content}")

                f.write(content)
            
            # if we have optional fields, check if they are present
            # in the example file and add them if they are missing
            if len(optional_fields) > 0:
                logging.debug(f"Checking for missing optional fields in {p}")
                has_changes = False
                with open(p, "r") as f:
                    content_data = json.loads(f.read())
                    is_list = isinstance(content_data, list)
                    if not is_list:
                        content_data = [content_data]
                    
                    for data in content_data:
                        for field in optional_fields:
                            if field not in data:
                                data[field] = None
                                has_changes = True
                    
                    if not is_list:
                        content_data = content_data[0]
                    content = json.dumps(content_data)

                if has_changes:
                    logging.debug(f"Added missing optional fields to {p}")
                    with open(p, "w") as f:
                        f.write(content)                

        path = f"{tmp_dir}" + "/{model}." + format
        delimiter = "array"
        server = Server(
            type="local",
            path=path,
            format=format,
            delimiter=delimiter,
        )
        run.log_info(f"Using {server} for testing the examples")
        return server    
    
    # monkey patch the to_property function to allow for nullable fields
    datacontract.export.jsonschema_converter.to_property = monkey_patch_to_property

    dc = DataContract(data_contract_file="contract.yml", examples=True)
    # monkey patch the _get_examples_server function to allow for optional fields
    dc._get_examples_server = monkey_patch_get_examples_server

    run = dc.test()
    run_result = run.result
    print("run result:", run.result)
    for log in run.logs[-10:]:
        print(log.message)
```

Which yields this output:
```bash
run result: passed
      Check that field SumSalesValue is present [PASSED]
      Check that field LastTransactionDate is present [PASSED]
      Check that required field CustomerID has no null values [PASSED]
      Check that field CustomerID has a minimum of 1 [PASSED]
      Check that required field AsOfDate has no null values [PASSED]
      Check that required field NumTransactions has no null values [PASSED]
      Check that field NumTransactions has a minimum of 0 [PASSED]
      Check that required field SumSalesValue has no null values [PASSED]
      Check that field SumSalesValue has a minimum of 0 [PASSED]
All is good. No failures. No warnings. No errors.
```
