### ISSUE TITLE
Fix BigQuery Array Type

### ISSUE THREAD

**Issue by ffernandez92** [datacontract/datacontract-cli#431]
As discussed in #421, there is a bug in how the BigQuery schema is converted from the DataContract schema to the BigQuery schema, specifically when handling arrays.

Example of the current behavior:

```
models:
  app: # matches with bigquery table name
    description: App dimensions
    type: table
    fields:
      (..others..)
      test_array:
        type: array
        items:
          type: string
        description: none.
```

Resulting BQ schema: 

```
{
        "name": "test_array",
        "type": "RECORD",
        "mode": "REPEATED",
        "description": "none.",
        "fields": [
          {
            "name": "test_array_1",
            "type": "STRING",
            "mode": "NULLABLE",
            "description": "",
            "maxLength": null
          }
        ]
      }
```

The correct BQ schema in the previous case should be:

```
{
        "mode": "REPEATED",
        "name": "test_array",
        "type": "STRING"
        "description": "none."
      },
```
