### ISSUE TITLE
Lint error on empty field description

### ISSUE THREAD

**Issue by tomyki** [datacontract/datacontract-cli#555]
Hello,
When I'm linting my data contract with this chunk of code I'm getting an error in linting

```
models:
  ABCD:
    description: Data ABCD view
    type: view
    fields:
      ID:
        type: number
        required: true
```

Error message:
Data contract is invalid, found the following errors:
1) Linter 'Objects have descriptions': Field 'ID' in model 
'ABCD' has empty description.

It is weird because description in field is said to be optional but it is throwing an error even though it is just warning,
