### ISSUE TITLE
Cannot execute test on column of type record(bigquery)

### ISSUE THREAD

**Issue by toshifumisuga** [datacontract/datacontract-cli#597]
# summary
When a column of type record is defined, it is recognized as a column of type json and the test cannot be executed.

# Execution Environments
* datatcontract-cli in version 0.10.16
* servers: bigquery

# sample.yml
I have omitted descriptions and other extraneous information.
```yaml
models:
  table_name:
    type: table
    fields:
      id:
        type: string
      products:
        type: record
        required: true
        fileds:
          product_name:
            type: string
```

# test execution result
A record is specified as the type, but it is recognized as a json.
```
25-01-18 04:52:43 INFO      table_name in bigquery
25-01-18 04:52:43 INFO        Check that field products has type JSON [FAILED]
25-01-18 04:52:43 INFO          fail_column_type_mismatch expected(JSON) actual(ARRAY<STRUCT<product_name STRING>>)
25-01-18 04:52:43 INFO          schema_measured = 
25-01-18 04:52:43 INFO  Oops! 1 failures. 0 warnings. 0 errors. 25 pass.
╭────────┬───────────────────────────────────────────────────────────────────┬───────┬────────────────────────────────────────────────────╮
│ Result │ Check                                                             │ Field │ Details                                            │
├────────┼───────────────────────────────────────────────────────────────────┼───────┼────────────────────────────────────────────────────┤
│ failed │ Check that field products has type JSON                           │       │ Type Mismatch, Expected Type: JSON; Actual Type:   │
│        │                                                                   │       │ ARRAY<STRUCT<product_name STRING>>                 │
```

When I specify json as a test, the following message is returned.
Since json is not an expected type, it is strange that json is returned for Expected Type.
```
25-01-18 05:05:41 ERROR Run operation failed:  Check that data contract YAML is valid - None - failed - data.models.sfdc_loc_tenants.fields.products.type 
must be one of ['number', 'decimal', 'numeric', 'int', 'integer', 'long', 'bigint', 'float', 'double', 'string', 'text', 'varchar', 'boolean', 'timestamp', 
'timestamp_tz', 'timestamp_ntz', 'date', 'array', 'map', 'object', 'record', 'struct', 'bytes', 'null'] - datacontract
```

I think the following part is returning JSON, is this the expected behavior?
I am aware that json can be defined as a BigQuery type.
https://cloud.google.com/bigquery/docs/json-data
Therefore, I think it is better to return json as return when json is specified on the yml side.

The following is executed on export, but returns the record type as json.
I could not decipher the code in detail, but I believe it is similar to what is done when test is executed.
https://github.com/datacontract/datacontract-cli/blob/7f2ea8d4bc15a0846ffaf7ce3416ae923316ca24/datacontract/export/bigquery_converter.py#L111-L112

**Comment by jochenchrist** [comment]
Thanks for reporting this. Fixed in https://github.com/datacontract/datacontract-cli/commit/cc9dad332fc1090763eb309642ee6c614da99689

**Comment by toshifumisuga** [comment]
Thank you for your prompt response to the correction！

I tried it at hand, but it doesn't seem to have resolved the error.
Is there any difference in my execution method or environment?
(The message `expected(JSON)` has been replaced by `expected(STRUCT<>)`)

```
root@f7244e47e513:/app/dbt_project# datacontract --version
0.10.18
root@f7244e47e513:/app/dbt_project# datacontract test --server dev datacontract_v4.yml --logs
Testing datacontract_v4.yml

Logs:
25-01-18 11:05:25 INFO  Testing data contract
25-01-18 11:05:26 INFO  Running tests for data contract my-data-contract-id with server dev
25-01-18 11:05:27 INFO  Running engine soda-core
25-01-18 11:05:27 INFO  Soda Core 3.3.20
25-01-18 11:05:31 INFO  Scan summary:
25-01-18 11:05:31 INFO  25/26 checks PASSED: 
25-01-18 11:05:31 INFO      table_name in bigquery
~~~~
25-01-18 11:05:31 INFO  1/26 checks FAILED: 
25-01-18 11:05:31 INFO      table_name in bigquery
25-01-18 11:05:31 INFO        Check that field products has type STRUCT<> [FAILED]
25-01-18 11:05:31 INFO          fail_column_type_mismatch expected(STRUCT<>) actual(ARRAY<STRUCT<product_name STRING, columnA 
DATE, columnB DATE, columnC BOOL, columnD FLOAT64>>)
25-01-18 11:05:31 INFO          schema_measured = 
25-01-18 11:05:31 INFO  Oops! 1 failures. 0 warnings. 0 errors. 25 pass.
╭────────┬───────────────────────────────────────────────────────────────────┬───────┬────────────────────────────────────────────────────╮
│ Result │ Check                                                             │ Field │ Details                                            │
├────────┼───────────────────────────────────────────────────────────────────┼───────┼────────────────────────────────────────────────────┤
│ failed │ Check that field products has type STRUCT<>                       │       │ Type Mismatch, Expected Type:STRUCT<>;             │
│        │                                                                   │       │ Actual Type: ARRAY<STRUCT<product_name STRING,     │
│        │                                                                   │       │ columnA DATE, columnB DATE, columnC BOOL,          │
│        │                                                                   │       │ columnD FLOAT64>>                                  │
```


### yml settings
The yml file used in the previous fix also contains the same record type column structure, so I can't think of a reason for the error in my environment...
https://github.com/datacontract/datacontract-cli/blob/main/tests/fixtures/bigquery/datacontract_complex.yaml#L15-L24


```yaml
dataContractSpecification: 1.1.0
id: my-data-contract-id
info:
  title: My Data Contract
  version: 0.0.1
servers:
  dev:
    type: bigquery
models:
  table_name:
    type: table
    fields:
      products:
        type: record
        fileds:
          product_name:
            type: string
          columnA:
            type: date
          columnB:
            type: date
          columnC:
            type: boolean
          columnD:
            type: float
```

### Schema definition on BQ
I will also send you a screencap of the schema definition on BigQuery just in case.
![Image](https://github.com/user-attachments/assets/3be24278-e892-4ecb-9368-6f112f0579d3)

**Comment by jochenchrist** [comment]
Please check the typo `fileds` -> `fields`

```
    fields:
      products:
        type: record
        fileds:
          product_name:
            type: string
          columnA:
            type: date
          columnB:
            type: date
          columnC:
            type: boolean
          columnD:
            type: float
```

**Comment by toshifumisuga** [comment]
Sorry for the omission of confirmation.
After modification, the following message is returned, but it is recognized that the expected part cannot be passed as a key of type.
```
25-01-18 11:48:44 INFO  1/26 checks FAILED: 
25-01-18 11:48:44 INFO      table_name in bigquery
25-01-18 11:48:44 INFO        Check that field products has type STRUCT<product_name STRING, columnA DATE, columnB 
DATE, columnC BOOL, columnD FLOAT64> [FAILED]
25-01-18 11:48:44 INFO          fail_column_type_mismatch expected(STRUCT<product_name STRING, columnA DATE, columnB 
DATE, columnC BOOL,columnD FLOAT64>) actual(ARRAY<STRUCT<product_name STRING, columnA DATE, columnB DATE, columnC BOOL,columnD FLOAT64>>)
25-01-18 11:48:44 INFO          schema_measured = 
25-01-18 11:48:44 INFO  Oops! 1 failures. 0 warnings. 0 errors. 25 pass.
```

**Comment by jochenchrist** [comment]
I `products` a repeatable field in BiqQuery?

Then you would need to specify it as array like this:

```

    fields:
      products:
        type: array
        items:
          type: record
          fields:
            product_name:
              type: string
            columnA:
              type: date
            columnB:
              type: date
            columnC:
              type: boolean
            columnD:
              type: float
```
