### ISSUE TITLE
Support AVRO format

### ISSUE THREAD

**Issue by jochenchrist** [datacontract/datacontract-cli#636]
Support AVRO

```
servers:
  production:
    type: s3
    environment: prod
    location: s3://datacontract-example-orders-latest/v2/{model}/*.avro
    format: avro
```
