### ISSUE TITLE
Linting does not seem to check CSV examples at the Model level

### ISSUE THREAD

**Issue by HodgeMJ** [datacontract/datacontract-cli#663]
## Description:

When linting a contract, field level examples are checked, but CSV examples provided at the model level don't seem to be checked.

### Example and output:
I've attached an example, but the CSV is shown below; the name field is an enumerated string, but if you set the name field in the first row to a number or a string not in the enumeration, it still passes the linter.

```yaml

    examples: 
      - type: csv 
        model: my_model
        description: An example of models data
        data: |
          Name,QuoteRequestSubmissionYear,QuoteRequestSubmissionYearMonth,QuoteRequestSubmissionDate,ActivityGUID
          1234,2023,202304,2023-04-22,"4bb8f05f-7317-47c9-8f14-d19a20df738a"
          "AAA",2023,202304,2023-04-22,"4bb8f05f-7317-47c9-8f14-d19a20df738a"
          "BBB",2023,202304,2023-04-22,"4bb8f05f-7317-47c9-8f14-d19a20df738a"
          "CCC",2023,202304,2023-04-22,"4bb8f05f-7317-47c9-8f14-d19a20df738a"

```

#### Linter output:

![Image](https://github.com/user-attachments/assets/91879627-7e60-424d-ab7d-091b5ca3402a)

#### Example Contract:

[testdatacontract.yaml.txt](https://github.com/user-attachments/files/18981102/testdatacontract.yaml.txt)
