### ISSUE TITLE
isXXX

### ISSUE THREAD

**Issue by jochenchrist** [datacontract/datacontract-cli#669]
Moved from https://github.com/datacontract/datacontract-specification/issues/115

By @jgperrin

ODCS v3 generator gives:

```yaml
  - name: customer_id
    logicalType: integer
    physicalType: integer
    isNullable: false
    isUnique: true
    primaryKey: true
    primaryKeyPosition: 1

```

ODCS elements are `nullable` and `unique` - we dropped the `is`.
