### ISSUE TITLE
LogicalTypes AVSC import

### ISSUE THREAD

**Issue by pixie79** [datacontract/datacontract-cli#687]
It looks like LogicalTypes are not correctly being imported when importing an AVSC file to a datacontract model. Whilst the import does not fail, if you try to export the model back to an AVSC file which I did as a round trip quick check the export fails as the model is not correct.

For example the follow items from an AVSC
```json
{
          "name" : "currentSelectionLiability",
          "type" : {
            "type" : "bytes",
            "logicalType" : "decimal",
            "precision" : 25,
            "scale" : 2
 },
{
    "name" : "raised",
    "type" : {
      "type" : "long",
      "logicalType" : "timestamp-millis"
    }
 }
```

get converted to:

```yaml
currentSelectionLiability:
    type: binary
    required: true
raised:
    type: long
    required: true
```

Example of the error message generated when doing the export back to an AVSC file is:
DataContractException: Run operation failed: [lint] Check that data contract YAML is valid - None - failed - 
data.models.fields.currentSelectionLiability.type must be one of ['number', 'decimal', 'numeric', 
'int', 'integer', 'long', 'bigint', 'float', 'double', 'string', 'text', 'varchar', 'boolean', 'timestamp', 'timestamp_tz', 
'timestamp_ntz', 'date', 'array', 'map', 'object', 'record', 'struct', 'bytes', 'null'] - datacontract

As you can see the import converted it to binary not bytes it also lost the precision and scale. Likewise on the time it should have been imported as a type of timestamp_tz

What is should have converted to is:
```yaml
currentSelectionLiability:
    type: decimal
    precision: 25
    scale: 2
    required: true
raised:
    type: timestamp_tz
    required: true
```
