### ISSUE TITLE
Feature: Support for fixed-length file format (maybe as new "server" type extension ?")

### ISSUE THREAD

**Issue by sjbenoist** [datacontract/datacontract-cli#739]
First of all, thank you for the work you did on this project, it is very interesting and useful

In our company we unfortunately have a significant number of old fixed-length format exchanges, which are a p*** in the a**  to manage, understand, document and so on. We would very much like to transition out of them, but as reality (and budgets) kick in, we see no other option but to put these under tighter control with data contracts, then working on conversion solutions.

Which leaves us with an open question: 
- How do we represent a fixed-length file format, (using fixed length for each field + ordinal positions) in a data contract ?

And since I have not found a way, that most likely implies some dev - maybe we could contribute but that would at least require some indications on the best way to proceed and declare such a contract ?

**Comment by jschoedl** [comment]
Hi @sjbenoist,
a lot of time has passed by now - not sure if your problem still persists. 
Anyways: I don't think that fixed-length file formats are common enough to get support in the Data Contract CLI. The approach I'd rather take is conversion to CSV, and then testing the CSV file. If you write a small CSV converter for yourself, you could even use the contract (with `customProperties`) to specify the column lengths, e.g. like this (AI-generated):

```yaml
apiVersion: v3.1.0
kind: DataContract
id: customers
name: Customers
version: 1.0.0
status: active
servers:
  - server: local
    type: local
    format: csv
    path: ./customers.csv
schema:
  - name: customers
    properties:
      - name: customer_id
        logicalType: string
        logicalTypeOptions: {pattern: '^C[0-9]{3}$'}
        customProperties: [{property: start, value: 1}, {property: length, value: 10}]
      - name: name
        logicalType: string
        logicalTypeOptions: {maxLength: 20}
        customProperties: [{property: start, value: 11}, {property: length, value: 20}]
      - name: balance
        logicalType: integer
        logicalTypeOptions: {minimum: 0}
        customProperties: [{property: start, value: 31}, {property: length, value: 8}]
      - name: amount
        logicalType: number
        customProperties: [{property: start, value: 39}, {property: length, value: 8}, {property: decimals, value: 2}]
      - name: opened
        logicalType: date
        customProperties: [{property: start, value: 47}, {property: length, value: 8}]
```

A small converter could then do the work:

```python
# fixed_to_csv.py <contract> <fixed-width file> <csv file>
import sys, yaml, duckdb

contract, source, target = sys.argv[1:4]
properties = yaml.safe_load(open(contract))["schema"][0]["properties"]
columns = []
for p in properties:
    custom = {c["property"]: c["value"] for c in p["customProperties"]}
    value = f"trim(substr(line, {custom['start']}, {custom['length']}))"
    if p.get("logicalType") == "date":  # YYYYMMDD -> ISO date
        value = f"strptime({value}, '%Y%m%d')::DATE"
    if "decimals" in custom:  # implied decimal point, e.g. 00123450 -> 1234.50
        value = f"{value}::DECIMAL(38,0) / 10 ** {custom['decimals']}"
    columns.append(f'{value} AS "{p["name"]}"')
duckdb.sql(f"""
    COPY (SELECT {", ".join(columns)}
          FROM read_csv('{source}', columns={{'line': 'VARCHAR'}}, delim=chr(1), header=false, quote='', escape=''))
    TO '{target}' (HEADER)
""")
```

```bash
python fixed_to_csv.py datacontract.yaml customers.txt customers.csv
datacontract test datacontract.yaml
```
