### ISSUE TITLE
Configure owner and id for imports

### ISSUE THREAD

**Issue by simonharrer** [datacontract/datacontract-cli#753]
When importing, one often needs to update the ID and set the owner afterwards. I want to do this right in the CLI call, so the resulting data contract contains the correct ID and owner.

## Before

```
$ datacontract import --format unity --unity-table-full-name mycatalog.myschema.mytable > mycontract.yaml
```

```yaml
dataContractSpecification: 1.1.0
id: my-data-contract-id
info:
  title: My Data Contract
  version: 0.0.1
models:
  country_codes:
    type: table
    title: country_codes
    fields:
      country_name:
        type: string
        required: false
      iso_alpha2:
        type: string
        required: false
      iso_alpha3:
        type: string
        required: false
```

add ID and owner manually afterwards using a code editor

## After

```
$ datacontract import --format unity --unity-table-full-name mycatalog.myschema.mytable --owner sales-team --id orders-v1 > mycontract.yaml
```

```yaml
dataContractSpecification: 1.1.0
id: orders-v1
info:
  title: My Data Contract
  version: 0.0.1
  owner: sales-team
models:
  country_codes:
    type: table
    title: country_codes
    fields:
      country_name:
        type: string
        required: false
      iso_alpha2:
        type: string
        required: false
      iso_alpha3:
        type: string
        required: false
```
