### ISSUE TITLE
Error while trying to connect to snowflake using SSO

### ISSUE THREAD

**Issue by pchojka** [datacontract/datacontract-cli#770]
Hello ! 
First time reporting an issue, apologies in advance if any information is missing

I'm trying to test and enforce a template data contract on a snowflake environment that is behind Microsoft ADSSO.
As regular username/password is not an option, I tried to include the `authenticator` attribute within my server configuration

**datacontract.yaml**
```
server:
  snow:
    type: snowflake
    authenticator: externalbrowser
    username: <myusername>
    password:  <dummy_password>
    account: <Account>
    database: <DB>
    schema: <Schema>
    role: <Role>
```

which produces the following result when testing the contract: 
```
25-05-21 14:35:05 INFO  Testing data contract
25-05-21 14:35:05 INFO  Running tests for data contract urn:datacontract:<contract_name> with server snow
25-05-21 14:35:05 INFO  Running engine soda-core
25-05-21 14:35:05 INFO  Soda Core 3.5.2
25-05-21 14:35:06 ERROR Could not connect to data source "snowflake": 250001 (08001): Failed to connect to DB: <MySnowflakeURL>. 
Incorrect username or password was specified.
```

I tried the same test using an equivalent configuration running on soda-engine, which was a success as i was able to connect through a link in my web browser

Is this wanted behavior / technical limitations ?

Thanks
