### ISSUE TITLE
Custom Quality Checks not included in the test.

### ISSUE THREAD

**Issue by julianbergerkoerber** [datacontract/datacontract-cli#784]
# Bug: Custom Checks not evaluated for `sql` quality checks

## Description

When defining a `sql` type quality check with a `mustBeGreaterThan` condition, the `mustBeGreaterThan` part of the check is not being evaluated by `datacontract-cli`. 

## Steps to Reproduce

1.  I Created a datacontract.yaml with the following model:

    ```yaml
    models:
      e_setpoint:
        description: >
          The e_setpoint table contains all information about the e_setpoint of the machine.
        type: table
        fields:
          min:
            description: Minimum value of the e_setpoint.
            type: string
            required: false
            quality:
              - type: sql
                description: there should always be a minimum value if the data_type is not string
                query: |
                  SELECT count(*) AS num_null_values
                  FROM {model}
                  WHERE min IS NULL AND data_type != 'string'
                mustBeGreaterThan: 0
    ```

2.  Ran the data contract check using `datacontract-cli`:

    ```bash
    datacontract test datacontract.yaml
    ```

## Result
The result only tested for existence of the min field and that it has a string data type:
| Result | Check                                | Field | Details |
|--------|--------------------------------------|-------|---------|
| passed | Check that field min is present      |       |         |
| passed | Check that field min has type STRING |       |         |

Am I doing something wrong?
