### ISSUE TITLE
Schema type check fails for type Variant on Databricks test

### ISSUE THREAD

**Issue by brunobrito89** [datacontract/datacontract-cli#786]
Hi all,

I was having a similar issue as described here on Issue #618.

I tested this schema:
```
items:
    type: array
    items:
      type: struct
      fields:
        item_name:
          type: string
        item_price:
          type: double
        quantity:
          type: long
```

However, got the following error:
```
🔴 data contract is invalid, found the following errors:
1) items Check that field items has type 
ARRAY<STRUCT<item_name STRING, item_price DOUBLE, quantity BIGINT>>: Type Mismatch, 

Expected Type: 
ARRAY<STRUCT<item_name STRING, item_price DOUBLE, quantity BIGINT>>; 

Actual 
Type: array<struct<item_name:string,item_price:double,quantity:bigint>>
```

I found #618 and saw @jochenchrist message so I decided to update to version **v0.10.28**, but I still got **the same error**.

Since I had the existing table in Databricks, I then decided to use `datacontract import` to get the table's schema using datacontract-cli. 

To my surprise, this was the schema I got:
```
      items:
        type: variant
        required: false
        config:
          databricksType: array<struct<item_name:string,item_price:double,quantity:bigint>>
```

I thought this was the new pattern due to some kind of inconsistency with Databricks.

However, if I try to run `datacontract test` against this schema, it seems the **variant type** does not exist.
```
data contract is invalid, found the following errors:

1) Check that data contract YAML is valid: data.models.orders.fields.items.type must be one of ['number', 'decimal', 'numeric', 'int', 'integer', 'long', 'bigint', 'float', 'double', 
'string', 'text', 'varchar', 'boolean', 'timestamp', 'timestamp_tz', 'timestamp_ntz', 'date', 'array', 'map', 'object', 'record', 'struct', 'bytes', 'null']
```

I also got the same **type: variant** for a `double` field:
```
      order_price:
        type: variant
        required: false
        config:
          databricksType: double
```

I'm confused. What is this `variant` type? Should it work? 
Is there any approach to work with nested fields to test on Databricks?

Thanks!!

**Comment by brunobrito89** [comment]
I was able to "fix" this with a workaround.

Since the `variant` type does not work with `datacontract test`, I changed the field type to `string` and used the `databricksType` with the expected type.

It went from this:
```
items:
    type: array
    items:
      type: struct
      fields:
        item_name:
          type: string
        item_price:
          type: double
        quantity:
          type: long
```
To this:
```
items:
   type: string
   required: false
   config:
       databricksType: array<struct<item_name:string,item_price:double,quantity:bigint>>

```

But still this doesn't seem right.

Doesn't it seems like there are two bugs?

1. Nested fields were not fixed on `v0.10.22`
2. The introduced `variant` type is not accepted on testing.
