### ISSUE TITLE
Unable to Connect to Google Cloud Storage Using datacontract-cli with S3 Configuration

### ISSUE THREAD

**Issue by yangauspost** [datacontract/datacontract-cli#794]
i have configured the yaml contract as follow, to connect to Google cloud storage through datacontract-cli, i have read the documentation, this configuration would work with GCP connect:
```
servers:
    production:
        type: s3
        endpointUrl: https://storage.googleapis.com/
        location: s3://bucket/file.csv
        format: csv
```
However, I received the following error message:
```
ERROR HTTP Error: Unable to connect to URL 
"https://bucket.s3.amazonaws.com/file
.csv": 404 (Not Found)
```
I have tried configuring a few different way, including changing the server type and location starting with gs: None of those works for me, I would still receive "unable to connect" the link would have "s3.amazonaws" in it. Would love your help with this, Thank you
